#![forbid(unsafe_code)]

use abdo_contracts::codegen::typescript_artifact;

#[test]
fn typescript_codegen_is_deterministic_and_exposes_only_strict_binary_contracts() {
    let first = typescript_artifact();
    let second = typescript_artifact();
    assert_eq!(first.as_bytes(), second.as_bytes());
    assert!(first.starts_with(
        "// @generated by abdo-contracts-codegen; DO NOT EDIT.\n\
         // Source of truth: crates/abdo-contracts/src/schema.rs\n"
    ));
    for required in [
        "export function encodeCommand",
        "export function decodeCommand",
        "export function encodeAdmissionEvent",
        "export function decodeAdmissionEvent",
        "export function encodeUnverifiedTrustReceipt",
        "export function decodeUnverifiedTrustReceipt",
        "export function canonicalTrustReceiptIntegrityBytes",
        "export const SCHEMA_FINGERPRINT",
        "const CODEC_SCHEMA_FINGERPRINT",
        "const CODEC_TYPE_DESCRIPTORS",
        "const CODEC_MESSAGE_TAGS",
        "export const CONTRACT_DESCRIPTOR = deepFreeze(",
        "INTRINSIC_REFLECT_OWN_KEYS(record)",
        "INTRINSIC_OBJECT_GET_OWN_PROPERTY_DESCRIPTOR(record, field)",
        "snapshotStructFields(value, descriptor.fields, typeName)",
        "INTRINSIC_UINT8_ARRAY_SET",
        "INTRINSIC_TYPED_ARRAY_TAG",
        "tag !== \"Uint8Array\"",
        "CODEC_MESSAGE_TAG_ENTRIES",
        "const message = snapshotByteArray(bytes, undefined, \"message\")",
        "schema fingerprint mismatch",
        "unsupported protocol version",
        "trailing message bytes",
    ] {
        assert!(first.contains(required), "missing {required}");
    }
    for forbidden_codec_dependency in [
        "writer.writeBytes(MESSAGE_MAGIC)",
        "writer.writeBytes(SCHEMA_FINGERPRINT)",
        "writer.writeBytes(TRUST_INTEGRITY_DOMAIN)",
        "writer.writeU16(MESSAGE_TAGS[typeName])",
        "const descriptor = TYPE_DESCRIPTORS",
        "Object.keys(value)",
        "this.bytes.slice(",
        ".push(",
        ".map(",
        ".find(",
        ".some(",
        ".includes(",
        "Object.entries(",
        "for (const ",
        "new Uint8Array(this.bytes)",
    ] {
        assert!(
            !first.contains(forbidden_codec_dependency),
            "codec depends on an exported mutable snapshot: {forbidden_codec_dependency}"
        );
    }
    for forbidden in [
        "JSON.stringify",
        "JSON.parse",
        "serde",
        "fetch(",
        "child_process",
        "crypto.random",
        "Math.random",
    ] {
        assert!(
            !first.contains(forbidden),
            "forbidden generated surface: {forbidden}"
        );
    }
}
