/**
 * `pr create` — فتحُ طلب دمجٍ على GitHub من الفرع الجاري. البند 4 في برنامج «أكفأ من Codex» (2026-09-28): Codex ينشئ PR
 * من مهمّته، وعندنا كانت المراجعةُ والنشرُ عليه (`review pr --post`) ولا إنشاءَ أصلاً.
 *
 * الترتيبُ جزءٌ من الميزة: الفرعُ ليس الافتراضيّ ⇦ فيه كوميتاتٌ على الأساس ⇦ **فحصُ الفرق الكامل أمنيّاً** (الخطيرُ يرفض) ⇦
 * **سؤالُ المالك صراحةً** (الدفعُ نشر — قاعدةُ «استأذن قبل كلّ دفعة») ⇦ الدفع ⇦ `gh pr create`. والجسدُ حتميّ من الكوميتات
 * والملفّات لا من نموذج: ما يُنشر باسم المالك يُكتب ممّا حدث لا ممّا يُروى.
 */

export interface PrCreateRequest { readonly title: string; readonly base?: string; readonly draft: boolean }

const BRANCH = /^[A-Za-z0-9._/-]{1,120}$/u

/** `pr create <عنوان> [--base <فرع>] [--draft]` أو «افتح PR <عنوان>» — والعنوانُ بعلامتَي تنصيص أو بقيّةُ السطر. */
export function parsePrCreate(body: string): PrCreateRequest | { readonly error: string } | undefined {
  const m = /^\/?(?:pr\s+create|افتح\s+(?:PR|pr|طلب\s+دمج))(?:\s+([\s\S]*))?$/u.exec(body.trim())
  if (m === null) return undefined
  let rest = (m[1] ?? "").trim()
  let base: string | undefined
  let draft = false
  const baseFlag = /(?:^|\s)--base\s+(\S+)/u.exec(rest)
  if (baseFlag !== null) {
    if (!BRANCH.test(baseFlag[1]!) || baseFlag[1]!.includes("..")) return { error: `--base اسمُ فرعٍ صالح، لا «${baseFlag[1]!.slice(0, 40)}».` }
    base = baseFlag[1]
    rest = rest.replace(baseFlag[0], " ")
  }
  if (/(?:^|\s)--draft(?=\s|$)/u.test(rest)) { draft = true; rest = rest.replace(/(?:^|\s)--draft(?=\s|$)/u, " ") }
  const quoted = /^["«“]([^"»”]+)["»”]$/u.exec(rest.trim())
  const title = (quoted?.[1] ?? rest).replace(/\s+/gu, " ").trim()
  if (title.length < 3) return { error: "pr create يحتاج عنواناً: pr create \"<العنوان>\" [--base main] [--draft]" }
  if (title.length > 200) return { error: "عنوانُ PR حتى 200 حرف." }
  return { title, ...(base === undefined ? {} : { base }), draft }
}

/** جسدُ PR من الوقائع: الكوميتاتُ (عنوانُ كلٍّ) والملفّات، وخاتمةٌ تقول من أنشأه. */
export function prBody(input: { readonly commits: readonly string[]; readonly files: readonly string[]; readonly scan: string }): string {
  const commits = input.commits.slice(0, 50).map((c) => `- ${c}`)
  const files = input.files.slice(0, 80).map((f) => `- \`${f}\``)
  return [
    "## التغييرات",
    ...commits, ...(input.commits.length > 50 ? [`- …و${input.commits.length - 50} كوميتاً آخر`] : []),
    "",
    `## الملفّات (${input.files.length})`,
    ...files, ...(input.files.length > 80 ? [`- …و${input.files.length - 80} ملفّاً آخر`] : []),
    "",
    "## فحصُ الفرق",
    input.scan,
    "",
    "🤖 Generated by the coding agent from this branch's commits",
  ].join("\n")
}

/** ما يمنع فتحَ PR قبل أيّ أثر — أو لا شيء. */
export function prBlocker(input: { readonly isRepo: boolean; readonly branch?: string; readonly base: string; readonly ahead: number; readonly remotes: readonly string[]; readonly dirty: number }): string | undefined {
  if (!input.isRepo) return "المشروعُ ليس مستودعَ git."
  if (input.branch === undefined) return "لا فرعَ جارٍ (HEAD منفصل) — أنشئ فرعاً أوّلاً."
  if (input.branch === input.base) return `الفرعُ الجاري هو الأساس «${input.base}» — PR يُفتح من فرع عملٍ إلى الأساس، لا منه إليه.`
  if (input.remotes.length === 0) return "لا بعيدَ (remote) للمستودع — لا مكانَ يُدفع إليه."
  if (input.ahead === 0) return `لا كوميتاتٍ على «${input.base}» في الفرع «${input.branch}» — لا شيءَ يُطلب دمجُه.`
  if (input.dirty > 0) return `في الشجرة ${input.dirty} تغييراً غيرَ مودَع — أودِعه أو أبعده قبل فتح PR كي يطابق ما يُنشر ما تراه.`
  return undefined
}
