import { afterEach, expect, test } from "bun:test"
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { extensionsRoot, loadLocalExtensions, localExtensionServers, localSkillInstructions, type ExtensionCatalog } from "../src/local-extensions"
const homes:string[]=[]
afterEach(()=>{for(const home of homes.splice(0))rmSync(home,{recursive:true,force:true})})
function fixture(){const home=mkdtempSync(join(tmpdir(),'abdo-extension-registry-'));homes.push(home);const settings=join(home,'settings.json'),root=extensionsRoot(settings),directory='1234567890abcdef1234567890abcdef';const folder=join(root,'packages',directory);mkdirSync(folder,{recursive:true});writeFileSync(join(folder,'SKILL.md'),'---\nname: proof\n---\nUse measured results.');writeFileSync(join(folder,'server.js'),'throw Error("never import this module")');const registry:ExtensionCatalog={schemaVersion:1,revision:1,packages:[{id:'proof',name:'Proof',version:'1.0.0',description:'Use measured results.',enabled:true,directory,skills:[{id:'proof',name:'proof',description:'Verify',file:'SKILL.md'}],mcpServers:[{id:'local',command:['node','${extension}/server.js'],secrets:[{env:'ABDO_EXT_TOKEN',handle:'custom-proof'}]}]}]};const save=()=>writeFileSync(join(root,'registry.json'),JSON.stringify(registry));save();return{home,settings,root,folder,registry,save}}
test('registered local skills require explicit selection; metadata never sends the skill body',()=>{const f=fixture();expect(localSkillInstructions(f.settings,'Do the work')).toBe('');expect(localSkillInstructions(f.settings,'/skill proof/proof\nDo the work')).toContain('Use measured results.');expect(JSON.stringify(loadLocalExtensions(f.settings))).not.toContain('---');expect(localSkillInstructions(f.settings,'Please discuss `/skill proof/proof`')).toBe('');f.registry.packages[0]!.enabled=false;f.save();expect(()=>localSkillInstructions(f.settings,'/skill proof/proof')).toThrow('not enabled');})
test('enabled MCP definitions resolve installed files and preserve configured server IDs',()=>{const f=fixture();const existing=[{id:'manual',command:['node','manual.js']}];expect(localExtensionServers(f.settings,existing)).toEqual([{id:'ext-proof-local',command:['node',join(f.folder,'server.js')],secrets:[{env:'ABDO_EXT_TOKEN',handle:'custom-proof'}]}]);expect(existing).toEqual([{id:'manual',command:['node','manual.js']}]);expect(localExtensionServers(f.settings,[{id:'ext-proof-local',command:['original']}])).toEqual([]);f.registry.packages[0]!.enabled=false;f.save();expect(localExtensionServers(f.settings)).toEqual([]);})
test('corrupt metadata, traversal, credential values and junctions fail closed',()=>{const f=fixture();const original=structuredClone(f.registry);for(const change of [(c:ExtensionCatalog)=>{c.packages[0]!.skills[0]!.file='../secret'},(c:ExtensionCatalog)=>{c.packages[0]!.description='sk-01234567890123456'},(c:ExtensionCatalog)=>{c.packages[0]!.mcpServers[0]!.command=['node','${extension}/../secret']},(c:ExtensionCatalog)=>{c.packages[0]!.mcpServers[0]!.secrets=[{env:'ABDO_SHELL_TOKEN',handle:'custom-proof'}]}]){Object.assign(f.registry,structuredClone(original));change(f.registry);f.save();const result=loadLocalExtensions(f.settings);expect(result.packages).toEqual([]);expect(result.error).toBeDefined();expect(JSON.stringify(result)).not.toContain('sk-01234567890123456');}Object.assign(f.registry,structuredClone(original));f.save();const outside=join(f.home,'outside');mkdirSync(outside);const link=join(f.folder,'linked');symlinkSync(outside,link,process.platform==='win32'?'junction':'dir');f.registry.packages[0]!.skills[0]!.file='linked/SKILL.md';f.save();writeFileSync(join(outside,'SKILL.md'),'not a selectable skill');expect(()=>localSkillInstructions(f.settings,'/skill proof/proof')).toThrow();})
test('edited skill bodies with credentials are refused before prompt construction',()=>{const f=fixture();writeFileSync(join(f.folder,'SKILL.md'),'a credential sk-01234567890123456');expect(()=>localSkillInstructions(f.settings,'/skill proof/proof')).toThrow('credential-like');expect(readFileSync(join(f.folder,'SKILL.md'),'utf8')).toContain('sk-');})
