/**
 * `pr create` — البند 4 (2026-09-28). وحدةٌ: الصيغة والموانع والجسد. وحيٌّ عبر exec على مستودعٍ حقيقيّ ببعيدٍ محلّيّ عارٍ:
 * المسارُ يبلغ سؤالَ المالك بالفرع والعنوان (التوأمُ الإيجابيّ)، ولا يُدفع شيءٌ بلا موافقة (exec لا مُوافِق فيه)؛
 * والموانعُ تقف قبل السؤال: PR من الأساس، وفرعٌ فيه سرّ.
 */
import { expect, test } from "bun:test"
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { parsePrCreate, prBlocker, prBody } from "../src/pr-create"
import { stripChildEnv } from "../../tools/src/env-strip"

test("the command in its forms, and its refusals named", () => {
  expect(parsePrCreate('pr create "Add login page" --base develop --draft')).toEqual({ title: "Add login page", base: "develop", draft: true })
  expect(parsePrCreate("افتح PR إصلاح عطل الدفع")).toEqual({ title: "إصلاح عطل الدفع", draft: false })
  expect(parsePrCreate("/pr create Fix it now")).toEqual({ title: "Fix it now", draft: false })
  expect(parsePrCreate("pr create")).toMatchObject({ error: expect.stringContaining("عنواناً") })
  expect(parsePrCreate("pr create x --base ../etc")).toMatchObject({ error: expect.stringContaining("--base") })
  expect(parsePrCreate("please create a pr")).toBeUndefined()
})

test("what blocks a PR before any effect", () => {
  const ok = { isRepo: true, branch: "feat/x", base: "main", ahead: 2, remotes: ["origin"], dirty: 0 }
  expect(prBlocker(ok)).toBeUndefined()
  expect(prBlocker({ ...ok, branch: "main" })).toContain("الأساس")
  expect(prBlocker({ ...ok, ahead: 0 })).toContain("لا كوميتات")
  expect(prBlocker({ ...ok, remotes: [] })).toContain("remote")
  expect(prBlocker({ ...ok, dirty: 3 })).toContain("غيرَ مودَع")
  const body = prBody({ commits: ["feat: a", "fix: b"], files: ["src/a.ts"], scan: "🛡 نظيف" })
  expect(body).toContain("- feat: a")
  expect(body).toContain("`src/a.ts`")
  expect(body).toContain("🤖 Generated by the coding agent")
})

const GH = ["ghp", "_", "Q1w2E3r4T5y6U7i8O9p0A1s2D3f4G5h6J7k8"].join("")

async function exec(task: string, setup: (git: (...a: string[]) => void, project: string) => void) {
  const server = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) {
    const payload = await request.json() as { stream?: boolean }
    if (payload.stream === false) return Response.json({ choices: [{ message: { role: "assistant", content: "ok" }, finish_reason: "stop" }] })
    return new Response(`data: ${JSON.stringify({ choices: [{ delta: { content: "ok" }, finish_reason: "stop" }] })}\n\ndata: [DONE]\n\n`, { headers: { "content-type": "text/event-stream" } })
  } })
  const home = mkdtempSync(join(tmpdir(), "abdo-pr-")), project = join(home, "proj"), remote = join(home, "remote.git"), settings = join(home, "settings.json")
  mkdirSync(project, { recursive: true })
  const run = (cwd: string, ...args: string[]) => Bun.spawnSync(["git", "-C", cwd, ...args], { stdout: "pipe", stderr: "pipe" })
  run(home, "init", "-q", "--bare", remote)
  const git = (...args: string[]) => { run(project, ...args) }
  git("init", "-q", "-b", "main"); git("config", "user.email", "t@example.com"); git("config", "user.name", "t"); git("config", "commit.gpgsign", "false")
  writeFileSync(join(project, "README.md"), "# p\n"); git("add", "README.md"); git("commit", "-q", "-m", "init")
  git("remote", "add", "origin", remote); git("push", "-q", "origin", "main")
  setup(git, project)
  writeFileSync(settings, JSON.stringify({
    language: "en", mode: "full-access", modelRole: "agent", routerGate: "off", project, railPolicy: "thin", workMode: "basic",
    agentModel: "fx/model", chatModel: "fx/model",
    plugins: { projectAwareness: false, sessionAwareness: false, generalAwareness: false, verifier: false, reviewer: false, delegation: false, inventory: false },
    superAbdo: { enabled: false, inspectEnvironment: false, isolateChanges: false, verifyResults: false, independentReview: false, maxRepairPasses: 0 },
    customProviders: [{ id: "fx", label: "fixture", baseUrl: `http://127.0.0.1:${server.port}/v1`, vaultKey: "", local: true, models: ["model"] }],
  }))
  const child = Bun.spawn([process.execPath, "packages/engine/src/cli.ts", "exec", task, "--project", project, "--mode", "full-access", "--json"], {
    cwd: resolve(import.meta.dir, "../../.."),
    env: { ...stripChildEnv(process.env).env, ABDO_CODE_SETTINGS: settings, ABDO_CODE_STATE_DIR: join(home, "state"), USERPROFILE: home, HOME: home, ABDO_VAULT_HOME: home },
    stdout: "pipe", stderr: "pipe",
  })
  const [stdout, stderr] = await Promise.all([new Response(child.stdout).text(), new Response(child.stderr).text(), child.exited])
  const remoteBranches = run(remote, "branch", "--list").stdout.toString()
  server.stop(true)
  rmSync(home, { recursive: true, force: true })
  const start = stdout.indexOf("{"), end = stdout.lastIndexOf("}")
  return { summary: start >= 0 ? JSON.parse(stdout.slice(start, end + 1)) : undefined, stdout, stderr, remoteBranches }
}

test("live: the flow reaches the owner's question with branch and title — and nothing is pushed without a yes", async () => {
  const r = await exec('pr create "Add greeting"', (git, project) => {
    git("checkout", "-q", "-b", "feat/greeting")
    writeFileSync(join(project, "greet.ts"), "export const hi = \"hello\"\n"); git("add", "greet.ts"); git("commit", "-q", "-m", "feat: greeting")
  })
  const asked = (r.summary?.approvalsDenied ?? []).join("\n")
  expect(asked, r.stderr.slice(-600)).toContain("feat/greeting")
  expect(asked).toContain("Add greeting")
  expect(r.remoteBranches).not.toContain("feat/greeting")
}, 150_000)

test("live, the twins that stop before the question: a PR from the base, and a branch carrying a secret", async () => {
  const fromBase = await exec('pr create "From main"', () => {})
  expect(fromBase.summary?.approvalsDenied ?? []).toEqual([])
  expect(fromBase.summary?.answer ?? "").toContain("الأساس")
  const secret = await exec('pr create "Leaky"', (git, project) => {
    git("checkout", "-q", "-b", "feat/leak")
    writeFileSync(join(project, "cfg.ts"), `export const t = "${GH}"\n`); git("add", "cfg.ts"); git("commit", "-q", "-m", "add cfg")
  })
  expect(secret.summary?.approvalsDenied ?? []).toEqual([])
  expect(secret.summary?.answer ?? "").toContain("secret:github_token")
  expect(`${secret.stdout}${secret.stderr}`).not.toContain(GH)
  expect(secret.remoteBranches).not.toContain("feat/leak")
}, 200_000)
