/**
 * P5c — the NAME of an isolated run's job object, and the durable record of it.
 *
 * ## Why a name at all
 *
 * Finding 17: the launch path created its job with `CreateJobObjectW(null, null)`.
 * An anonymous job's handle is stack-local to the helper invocation that made
 * it, so when a host died with a child still running, nothing could ever reach
 * that job again. `assessLiveness` had no honest answer but "defer", and
 * `startup.ts` turns a deferral into a BLOCKED bootstrap — one crash with a
 * surviving child stopped every later run on the machine.
 *
 * ## What this module is careful about
 *
 * **The name is not a secret and not a capability.** Anyone who can guess it can
 * try to create it; what stops them is the job's protected descriptor and the
 * collision rule in the helper, not the unguessability of the string. The nonce
 * is here to keep two runs from colliding, not to keep an attacker out.
 *
 * **Nothing in the name is model-controlled.** Every component is either
 * host-derived (the SID hash, the session), generated by the host's own CSPRNG
 * (the run id, the operation id, the nonce), or a monotonic counter (the fencing
 * token). No caller text, no path, no executable name reaches it.
 *
 * **The derivation is duplicated in Rust and must not drift.** `src/job.rs`
 * carries the same rule so the helper can PROVE an identity it was merely told —
 * it recomputes the prefix from the runId/operationId/fencingToken a caller
 * claims and refuses a name that does not start with it. A test compares the two
 * implementations, in the same spirit as the protocol-version agreement test,
 * because two copies of one rule in two languages is exactly the drift that
 * once cost seven identity tests.
 */
import { createHash, randomBytes } from "node:crypto"

/** Must equal `JOB_NAME_PREFIX` in `src/job.rs`. */
export const JOB_NAME_PREFIX = String.raw`Local\Abdo-IsolatedRun-`

/**
 * `Local\` scopes the object to the caller's SESSION namespace
 * (`\Sessions\<n>\BaseNamedObjects\`) rather than the machine-wide `Global\`
 * one. A job that exists in one session cannot be opened, squatted or
 * terminated from another, and nothing about this object wants to be visible
 * machine-wide.
 */
// NOT `String.raw` here, and that is deliberate: a raw template cannot END in a
// backslash — the backslash escapes the closing backtick and the literal runs on
// into the rest of the file. (Caught by the compiler; it is the fourth
// appearance of the `String.raw` trap family this sprint has recorded.) A
// doubled backslash in a normal string is unambiguous and the path-literal lint
// is satisfied, since an even-length run is exactly what it wants to see.
const LOCAL_PREFIX = "Local\\"

/** Must equal `MAX_JOB_NAME` in `src/job.rs`. */
const MAX_JOB_NAME = 200

/**
 * The host SID folded to a fixed-width token that is safe inside an object name.
 *
 * A SID is full of hyphens and would be indistinguishable from the name's own
 * separators; hashing also keeps the name bounded. Sixteen hex characters is
 * not a secret — see the note above — it only has to make two users' names
 * differ.
 */
export const hostSidHash = (hostSid: string): string => createHash("sha256").update(hostSid.toLowerCase()).digest("hex").slice(0, 16)

/**
 * Everything in the name except the nonce.
 *
 * THE SHARED DERIVATION RULE. Because the runId, operationId and fencingToken
 * are baked into the string, a caller cannot present run A's job name alongside
 * run B's evidence, and a STALE owner cannot name a job that was minted under a
 * higher fencing token — its own token is part of what it would have to
 * produce. The helper recomputes this and refuses a mismatch.
 */
export const jobNamePrefixFor = (hostSid: string, runId: string, operationId: string, fencingToken: number): string =>
  `${JOB_NAME_PREFIX}${hostSidHash(hostSid)}-${runId}-${operationId}-${fencingToken}-`

/**
 * Mirrors `is_valid_job_name` in `src/job.rs`.
 *
 * The single-backslash rule is the load-bearing one: a second backslash would
 * let a name walk out of the session namespace (`Local\..\..\Global\x`) or
 * address a nested object directory, and either defeats the session scoping the
 * `Local\` prefix exists for. "No raw paths after the prefix" is enforced as a
 * closed charset rather than as a blocklist of the separators we thought of.
 */
export function isValidJobName(name: string): boolean {
  if (!name.startsWith(JOB_NAME_PREFIX) || name.length > MAX_JOB_NAME) return false
  // The prefix alone is not a name — see the matching note in `src/job.rs`.
  if (name.length <= JOB_NAME_PREFIX.length) return false
  const tail = name.slice(LOCAL_PREFIX.length)
  if (tail.length === 0 || tail.includes("\\")) return false
  return /^[A-Za-z0-9_-]+$/.test(tail)
}

/** 128 CSPRNG bits, so two runs cannot land on one name. */
const newNonce = (): string => randomBytes(16).toString("hex")

export interface JobIdentity {
  /** The exact object name. Recorded durably BEFORE the process is created. */
  readonly jobName: string
  readonly sessionId: number
  readonly hostSid: string
  readonly runId: string
  readonly operationId: string
  readonly fencingToken: number
}

/**
 * Mint the identity for one launch attempt.
 *
 * Called BEFORE anything is created, so its result can be journalled first —
 * the name is the only route back to an orphaned tree, and a name that was not
 * written down before the process existed is a name that may not have been
 * written down at all.
 */
export function newJobIdentity(input: { hostSid: string; sessionId: number; runId: string; operationId: string; fencingToken: number }): JobIdentity {
  const jobName = `${jobNamePrefixFor(input.hostSid, input.runId, input.operationId, input.fencingToken)}${newNonce()}`
  if (!isValidJobName(jobName)) {
    // A derivation that produced an unusable name is a bug in this file, not a
    // caller error, and it must not reach the helper as a mystery refusal.
    throw new Error(`job_name_underivable: ${JSON.stringify(jobName)} is not a name the helper will accept`)
  }
  return { jobName, sessionId: input.sessionId, hostSid: input.hostSid, runId: input.runId, operationId: input.operationId, fencingToken: input.fencingToken }
}

/**
 * The job's own events.
 *
 * DELIBERATELY OUTSIDE `LIFECYCLE_ORDER`. That list is a closed, gap-checked
 * contract of seventeen events and `validateLifecycleSequence` rejects anything
 * it does not know; adding three more would rewrite the meaning of every
 * recorded run. These are recorded ALONGSIDE it, exactly as `execution_run.*`
 * and `run.refused` already are, and anything reading the lifecycle chain
 * filters to `LIFECYCLE_ORDER` (`readRunLifecycle` does).
 *
 * They live in the RUN's aggregate — `winiso:isorun:<runId>` — and that is not
 * incidental. Finding 14: the ACL grant events were written to a shared
 * aggregate that isolated-run recovery never reads, so `run.grants` was ALWAYS
 * empty, recovery restored nothing and reported `reclaimed`. Evidence that
 * recovery cannot reach is evidence that does not exist. Recovery reads this
 * aggregate, so the job's name is written here.
 */
export const JobEvents = {
  /** Intent. Carries the exact name, BEFORE any object or process exists. */
  CreateRequested: "isorun.job.create_requested",
  /** Completion, from the helper's own read-back of the object it created. */
  Created: "isorun.job.created",
  /**
   * P5c2. The TRUSTED KEEPER is holding this job's name — recorded after the
   * keeper proved itself and BEFORE the target process was created.
   *
   * This is the event recovery needs most, and its position in the file is the
   * reason: a run with `job.created` but no `keeper.ready` never got as far as
   * launching anything, and a run with `keeper.ready` has a pid + creation time
   * recovery can check before it trusts the job name at all.
   */
  KeeperReady: "isorun.job.keeper_ready",
  /** The initial process, its identity, and its proven membership. */
  ProcessCreated: "isorun.job.process_created",
} as const

export type JobEvent = (typeof JobEvents)[keyof typeof JobEvents]

/** What `job.created` records, all of it measured rather than requested. */
export interface JobCreatedEvidence {
  readonly jobName: string
  readonly sessionId: number
  readonly securityDescriptor: string
  readonly securityDescriptorHash: string
  readonly limitsHash: string
  readonly limitFlags: number
  readonly hostSid: string
  readonly helperBinaryHash: string
  readonly helperProtocolVersion: number
}

/**
 * P5c2. What `keeper.ready` records: the identity of the process that is
 * holding this job's name open.
 *
 * `keeperPid` WITH `keeperStartTime`, never the pid alone. Windows reuses pids
 * aggressively, and a recovery that accepted a bare pid would eventually decide
 * a stranger was the keeper — then trust the job name on the strength of it.
 */
export interface JobKeeperEvidence {
  readonly jobName: string
  readonly sessionId: number
  readonly keeperPid: number
  /** Decimal FILETIME digits. A STRING because a FILETIME exceeds 2^53. */
  readonly keeperStartTime: string
  readonly keeperImage: string
  readonly runId: string
  readonly operationId: string
  /** A STRING for the same reason the times are: it is an identity, not a count. */
  readonly fencingToken: string
}

/** What `process.created` records. */
export interface JobProcessEvidence {
  readonly jobName: string
  readonly sessionId: number
  readonly pid: number
  /** Decimal FILETIME digits. A STRING because a FILETIME exceeds 2^53. */
  readonly startTime: string
  readonly actualImagePath: string
  readonly tokenAppContainerSid: string
  readonly isAppContainer: boolean
  readonly assignedToJob: boolean
  readonly isProcessInJob: boolean
  /**
   * P5c2. THE KEEPER ACKNOWLEDGED ARMING before this process was resumed.
   *
   * Replaces `childKeepAliveHandle`, which recorded that a job handle had been
   * duplicated into the TARGET — a handle the target owned and could close, so
   * the field recorded an intention rather than a guarantee. This one is an
   * acknowledgement from a process the target cannot reach.
   */
  readonly keeperArmed: boolean
  readonly keeperPid: number
  readonly keeperStartTime: string
}

/**
 * Parse the helper's evidence file.
 *
 * JSONL, one line per fact, in the order the facts became true: the job existed
 * and was verified BEFORE any process did. A single rewritten object would lose
 * exactly that ordering, which is the property the file is here to record.
 *
 * A missing or truncated file is NOT an error. The name — the only thing
 * recovery strictly needs — was journalled before the helper ever started, and
 * a host killed mid-launch is the normal case this whole phase is about.
 */
export function parseJobEvidence(text: string): { created?: JobCreatedEvidence; keeper?: JobKeeperEvidence; process?: JobProcessEvidence } {
  const out: { created?: JobCreatedEvidence; keeper?: JobKeeperEvidence; process?: JobProcessEvidence } = {}
  for (const line of text.split("\n")) {
    const t = line.trim()
    if (t.length === 0) continue
    let parsed: Record<string, unknown>
    try {
      parsed = JSON.parse(t) as Record<string, unknown>
    } catch {
      // A torn final line is what a killed process leaves. The lines before it
      // are still true, so it is skipped rather than failing the whole read.
      continue
    }
    if (parsed.event === "job.created") out.created = parsed as unknown as JobCreatedEvidence
    if (parsed.event === "keeper.ready") out.keeper = parsed as unknown as JobKeeperEvidence
    if (parsed.event === "process.created") out.process = parsed as unknown as JobProcessEvidence
  }
  return out
}
