//! Deterministic TypeScript generation from [`crate::schema::PROTOCOL_DESCRIPTOR`].

use std::fmt::Write as _;

use crate::schema::{
    MessageDescriptor, ProtocolDescriptor, RuleDescriptor, TypeDescriptor, TypeKind,
    PROTOCOL_DESCRIPTOR,
};
use crate::{
    encode_frame, CancelCommand, CancellationId, CauseRef, Command, CommandId, ProposalId,
    RootCause, Scope, WorkspaceScope,
};

pub const GOLDEN_CANCEL_COMMAND_BINARY: &str = "cancel-command-v1.bin";
pub const GOLDEN_CANCEL_COMMAND_MANIFEST: &str = "cancel-command-v1.json";

/// Render the canonical TypeScript artifact.
pub fn typescript_artifact() -> String {
    render(&PROTOCOL_DESCRIPTOR)
}

/// Rust-authored canonical bytes consumed by both Rust and Bun parity tests.
pub fn golden_cancel_command_bytes() -> Vec<u8> {
    encode_frame(&Command::Cancel(Box::new(CancelCommand {
        command_id: CommandId::try_from_u128(1).expect("non-zero golden ID"),
        cancellation_id: CancellationId::try_from_u128(2).expect("non-zero golden ID"),
        proposal_id: ProposalId::try_from_u128(3).expect("non-zero golden ID"),
        scope: Scope::Workspace(Box::new(WorkspaceScope)),
        cause: CauseRef::Root(Box::new(RootCause)),
        requested_at_ms: 4,
    })))
    .expect("the built-in golden command is canonical")
}

/// Human-readable diagnostic shape for the binary fixture. JSON is not a wire
/// format and never participates in decoding or authority decisions.
pub fn golden_cancel_command_manifest() -> String {
    let frame = golden_cancel_command_bytes();
    format!(
        concat!(
            "{{\n",
            "  \"_diagnostic_only\": true,\n",
            "  \"fixture\": \"cancel-command-v1\",\n",
            "  \"message\": \"Command.Cancel\",\n",
            "  \"protocol_version\": {},\n",
            "  \"schema_fingerprint_hex\": \"{}\",\n",
            "  \"frame_length\": {},\n",
            "  \"frame_hex\": \"{}\",\n",
            "  \"shape\": {{\n",
            "    \"tag\": \"Cancel\",\n",
            "    \"command_id\": \"1\",\n",
            "    \"cancellation_id\": \"2\",\n",
            "    \"proposal_id\": \"3\",\n",
            "    \"scope\": \"Workspace\",\n",
            "    \"cause\": \"Root\",\n",
            "    \"requested_at_ms\": \"4\"\n",
            "  }}\n",
            "}}\n",
        ),
        PROTOCOL_DESCRIPTOR.version,
        hex_bytes(&PROTOCOL_DESCRIPTOR.schema_fingerprint),
        frame.len(),
        hex_bytes(&frame),
    )
}

fn render(protocol: &ProtocolDescriptor) -> String {
    let mut output = String::new();
    output.push_str("// @generated by abdo-contracts-codegen; DO NOT EDIT.\n");
    output.push_str("// Source of truth: crates/abdo-contracts/src/schema.rs\n");
    output.push_str("// Fixed-order little-endian codec. No JSON is authoritative.\n\n");

    output.push_str(
        "const INTRINSIC_ARRAY_IS_ARRAY = Array.isArray\n\
         const INTRINSIC_BIGINT = BigInt\n\
         const INTRINSIC_NUMBER = Number\n\
         const INTRINSIC_NUMBER_IS_INTEGER = Number.isInteger\n\
         const INTRINSIC_NUMBER_IS_SAFE_INTEGER = Number.isSafeInteger\n\
         const INTRINSIC_OBJECT_CREATE = Object.create\n\
         const INTRINSIC_OBJECT_DEFINE_PROPERTY = Object.defineProperty\n\
         const INTRINSIC_OBJECT_FREEZE = Object.freeze\n\
         const INTRINSIC_OBJECT_GET_OWN_PROPERTY_DESCRIPTOR = Object.getOwnPropertyDescriptor\n\
         const INTRINSIC_OBJECT_GET_PROTOTYPE_OF = Object.getPrototypeOf\n\
         const INTRINSIC_OBJECT_PROTOTYPE = Object.prototype\n\
         const INTRINSIC_OBJECT_VALUES = Object.values\n\
         const INTRINSIC_REFLECT_APPLY = Reflect.apply\n\
         const INTRINSIC_REFLECT_OWN_KEYS = Reflect.ownKeys\n\
         const INTRINSIC_UINT8_ARRAY = Uint8Array\n\
         const INTRINSIC_UINT8_ARRAY_SET = Uint8Array.prototype.set\n\
         const INTRINSIC_TYPED_ARRAY_PROTOTYPE = INTRINSIC_OBJECT_GET_PROTOTYPE_OF(Uint8Array.prototype)\n\
         const INTRINSIC_TYPED_ARRAY_LENGTH = INTRINSIC_OBJECT_GET_OWN_PROPERTY_DESCRIPTOR(\n\
         \x20 INTRINSIC_TYPED_ARRAY_PROTOTYPE,\n\
         \x20 \"length\",\n\
         )?.get\n\
         const INTRINSIC_TYPED_ARRAY_TAG = INTRINSIC_OBJECT_GET_OWN_PROPERTY_DESCRIPTOR(\n\
         \x20 INTRINSIC_TYPED_ARRAY_PROTOTYPE,\n\
         \x20 Symbol.toStringTag,\n\
         )?.get\n\n\
         function copyConstantBytes(bytes: readonly number[]): Uint8Array {\n\
         \x20 const snapshot = new INTRINSIC_UINT8_ARRAY(bytes.length)\n\
         \x20 for (let index = 0; index < bytes.length; index += 1) snapshot[index] = bytes[index]!\n\
         \x20 return snapshot\n\
         }\n\n\
         function deepFreeze<T>(value: T): T {\n\
         \x20 if (typeof value === \"object\" && value !== null) {\n\
         \x20   const children = INTRINSIC_OBJECT_VALUES(value as Record<string, unknown>)\n\
         \x20   for (let index = 0; index < children.length; index += 1) deepFreeze(children[index])\n\
         \x20   INTRINSIC_OBJECT_FREEZE(value)\n\
         \x20 }\n\
         \x20 return value\n\
         }\n\n",
    );

    writeln!(
        output,
        "export const PROTOCOL_NAME = {:?} as const",
        protocol.name
    )
    .expect("String formatting cannot fail");
    writeln!(
        output,
        "export const PROTOCOL_VERSION = {} as const",
        protocol.version
    )
    .expect("String formatting cannot fail");
    writeln!(
        output,
        "export const MAX_MESSAGE_BYTES = {} as const",
        protocol.max_message_bytes
    )
    .expect("String formatting cannot fail");
    writeln!(
        output,
        "const CODEC_MESSAGE_MAGIC = INTRINSIC_OBJECT_FREEZE([{}] as const)",
        comma_bytes(&protocol.magic)
    )
    .expect("String formatting cannot fail");
    writeln!(
        output,
        "const CODEC_SCHEMA_FINGERPRINT = INTRINSIC_OBJECT_FREEZE([{}] as const)",
        comma_bytes(&protocol.schema_fingerprint)
    )
    .expect("String formatting cannot fail");
    writeln!(
        output,
        "const CODEC_TRUST_INTEGRITY_DOMAIN = INTRINSIC_OBJECT_FREEZE([{}] as const)\n",
        comma_bytes(protocol.trust_integrity_domain)
    )
    .expect("String formatting cannot fail");
    output.push_str(
        "// These typed-array exports are detached compatibility snapshots. The codec never reads them.\n\
         export const MESSAGE_MAGIC = copyConstantBytes(CODEC_MESSAGE_MAGIC)\n\
         export const SCHEMA_FINGERPRINT = copyConstantBytes(CODEC_SCHEMA_FINGERPRINT)\n\
         export const TRUST_INTEGRITY_DOMAIN = copyConstantBytes(CODEC_TRUST_INTEGRITY_DOMAIN)\n\n",
    );

    render_types(&mut output, protocol.types);
    render_descriptors(&mut output, protocol);
    output.push_str(TYPESCRIPT_RUNTIME);
    render_message_functions(&mut output, protocol.messages);
    output
}

fn render_types(output: &mut String, types: &[TypeDescriptor]) {
    for descriptor in types {
        match descriptor.kind {
            TypeKind::Id128 => {
                writeln!(
                    output,
                    "export type {} = bigint & {{ readonly __brand: {:?} }}\n",
                    descriptor.name, descriptor.name
                )
                .expect("String formatting cannot fail");
            }
            TypeKind::FixedBytes { .. } => {
                writeln!(
                    output,
                    "export type {} = Uint8Array & {{ readonly __brand: {:?} }}\n",
                    descriptor.name, descriptor.name
                )
                .expect("String formatting cannot fail");
            }
            TypeKind::Unit => {
                writeln!(
                    output,
                    "export type {} = Readonly<Record<string, never>>\n",
                    descriptor.name
                )
                .expect("String formatting cannot fail");
            }
            TypeKind::Struct { fields, .. } => {
                writeln!(output, "export interface {} {{", descriptor.name)
                    .expect("String formatting cannot fail");
                for field in fields {
                    writeln!(
                        output,
                        "  readonly {}: {}",
                        field.name,
                        typescript_type(field.type_name)
                    )
                    .expect("String formatting cannot fail");
                }
                output.push_str("}\n\n");
            }
            TypeKind::Enum { variants } => {
                write!(output, "export type {} = ", descriptor.name)
                    .expect("String formatting cannot fail");
                for (index, variant) in variants.iter().enumerate() {
                    if index != 0 {
                        output.push_str(" | ");
                    }
                    write!(output, "{:?}", variant.name).expect("String formatting cannot fail");
                }
                output.push_str("\n\n");
            }
            TypeKind::Union { variants } => {
                writeln!(output, "export type {} =", descriptor.name)
                    .expect("String formatting cannot fail");
                for variant in variants {
                    writeln!(
                        output,
                        "  | {{ readonly tag: {:?}; readonly value: {} }}",
                        variant.name,
                        variant.payload_type.expect("union variants have payloads")
                    )
                    .expect("String formatting cannot fail");
                }
                output.push('\n');
            }
        }
    }
}

fn render_descriptors(output: &mut String, protocol: &ProtocolDescriptor) {
    output.push_str(
        "type RuntimeRule =\n\
         | { readonly kind: \"nonZeroU64\"; readonly field: string }\n\
         | { readonly kind: \"nonZeroBytes\"; readonly field: string }\n\
         | { readonly kind: \"lessThanU64\"; readonly lower: string; readonly upper: string }\n\
         | { readonly kind: \"maxSpanU64\"; readonly lower: string; readonly upper: string; readonly maximum: bigint }\n\n\
         interface RuntimeField { readonly name: string; readonly typeName: string }\n\
         interface RuntimeVariant { readonly name: string; readonly tag: number; readonly payloadType?: string }\n\n\
         type RuntimeTypeDescriptor =\n\
         | { readonly kind: \"id128\" }\n\
         | { readonly kind: \"fixedBytes\"; readonly length: number }\n\
         | { readonly kind: \"unit\" }\n\
         | { readonly kind: \"struct\"; readonly fields: readonly RuntimeField[]; readonly rules: readonly RuntimeRule[]; readonly integrityField?: string }\n\
         | { readonly kind: \"enum\"; readonly variants: readonly RuntimeVariant[] }\n\
         | { readonly kind: \"union\"; readonly variants: readonly RuntimeVariant[] }\n\n\
         const CODEC_TYPE_DESCRIPTORS: Readonly<Record<string, RuntimeTypeDescriptor>> = deepFreeze({\n",
    );

    for descriptor in protocol.types {
        write!(output, "  {:?}: ", descriptor.name).expect("String formatting cannot fail");
        render_type_descriptor(output, descriptor);
        output.push_str(",\n");
    }
    output.push_str("})\n\n");

    output.push_str("const CODEC_MESSAGE_TAGS = deepFreeze({\n");
    for message in protocol.messages {
        writeln!(output, "  {}: {},", message.type_name, message.tag)
            .expect("String formatting cannot fail");
    }
    output.push_str("} as const)\n\n");

    output.push_str("const CODEC_MESSAGE_TAG_ENTRIES = deepFreeze([\n");
    for message in protocol.messages {
        writeln!(
            output,
            "  [{:?}, {}] as const,",
            message.type_name, message.tag
        )
        .expect("String formatting cannot fail");
    }
    output.push_str("] as const)\n\n");

    output.push_str("export const MESSAGE_TAGS = deepFreeze({\n");
    for message in protocol.messages {
        writeln!(output, "  {}: {},", message.type_name, message.tag)
            .expect("String formatting cannot fail");
    }
    output.push_str("} as const)\n\n");

    writeln!(output, "export const CONTRACT_DESCRIPTOR = deepFreeze({{")
        .expect("String formatting cannot fail");
    output.push_str("  name: PROTOCOL_NAME,\n");
    output.push_str("  version: PROTOCOL_VERSION,\n");
    writeln!(
        output,
        "  magic: [{}] as const,",
        comma_bytes(&protocol.magic)
    )
    .expect("String formatting cannot fail");
    output.push_str("  maxMessageBytes: MAX_MESSAGE_BYTES,\n");
    writeln!(
        output,
        "  schemaFingerprint: [{}] as const,",
        comma_bytes(&protocol.schema_fingerprint)
    )
    .expect("String formatting cannot fail");
    writeln!(
        output,
        "  trustIntegrityDomain: [{}] as const,",
        comma_bytes(protocol.trust_integrity_domain)
    )
    .expect("String formatting cannot fail");
    output.push_str("  types: {\n");
    for descriptor in protocol.types {
        write!(output, "    {:?}: ", descriptor.name).expect("String formatting cannot fail");
        render_type_descriptor(output, descriptor);
        output.push_str(",\n");
    }
    output.push_str("  },\n");
    output.push_str("  messages: {\n");
    for message in protocol.messages {
        writeln!(output, "    {}: {},", message.type_name, message.tag)
            .expect("String formatting cannot fail");
    }
    output.push_str("  },\n");
    output.push_str("} as const)\n\n");
}

fn render_type_descriptor(output: &mut String, descriptor: &TypeDescriptor) {
    match descriptor.kind {
        TypeKind::Id128 => output.push_str("{ kind: \"id128\" }"),
        TypeKind::FixedBytes { length } => {
            write!(output, "{{ kind: \"fixedBytes\", length: {length} }}")
                .expect("String formatting cannot fail");
        }
        TypeKind::Unit => output.push_str("{ kind: \"unit\" }"),
        TypeKind::Struct {
            fields,
            rules,
            integrity_field,
        } => {
            output.push_str("{ kind: \"struct\", fields: [");
            for (index, field) in fields.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                write!(
                    output,
                    "{{ name: {:?}, typeName: {:?} }}",
                    field.name, field.type_name
                )
                .expect("String formatting cannot fail");
            }
            output.push_str("], rules: [");
            for (index, rule) in rules.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                render_rule_descriptor(output, rule);
            }
            output.push(']');
            if let Some(field) = integrity_field {
                write!(output, ", integrityField: {field:?}")
                    .expect("String formatting cannot fail");
            }
            output.push_str(" }");
        }
        TypeKind::Enum { variants } | TypeKind::Union { variants } => {
            let kind = if matches!(descriptor.kind, TypeKind::Enum { .. }) {
                "enum"
            } else {
                "union"
            };
            write!(output, "{{ kind: {kind:?}, variants: [")
                .expect("String formatting cannot fail");
            for (index, variant) in variants.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                write!(output, "{{ name: {:?}, tag: {}", variant.name, variant.tag)
                    .expect("String formatting cannot fail");
                if let Some(payload) = variant.payload_type {
                    write!(output, ", payloadType: {payload:?}")
                        .expect("String formatting cannot fail");
                }
                output.push_str(" }");
            }
            output.push_str("] }");
        }
    }
}

fn render_rule_descriptor(output: &mut String, rule: &RuleDescriptor) {
    match rule {
        RuleDescriptor::NonZeroU64 { field } => {
            write!(output, "{{ kind: \"nonZeroU64\", field: {field:?} }}")
                .expect("String formatting cannot fail");
        }
        RuleDescriptor::NonZeroBytes { field } => {
            write!(output, "{{ kind: \"nonZeroBytes\", field: {field:?} }}")
                .expect("String formatting cannot fail");
        }
        RuleDescriptor::LessThanU64 { lower, upper } => {
            write!(
                output,
                "{{ kind: \"lessThanU64\", lower: {lower:?}, upper: {upper:?} }}"
            )
            .expect("String formatting cannot fail");
        }
        RuleDescriptor::MaxSpanU64 {
            lower,
            upper,
            maximum,
        } => {
            write!(
                output,
                "{{ kind: \"maxSpanU64\", lower: {lower:?}, upper: {upper:?}, maximum: {maximum}n }}"
            )
            .expect("String formatting cannot fail");
        }
    }
}

fn render_message_functions(output: &mut String, messages: &[MessageDescriptor]) {
    for message in messages {
        writeln!(
            output,
            "export function encode{}(value: {}): Uint8Array {{",
            message.type_name, message.type_name
        )
        .expect("String formatting cannot fail");
        writeln!(
            output,
            "  return encodeFrame({:?}, value)",
            message.type_name
        )
        .expect("String formatting cannot fail");
        output.push_str("}\n\n");
        writeln!(
            output,
            "export function decode{}(bytes: Uint8Array): {} {{",
            message.type_name, message.type_name
        )
        .expect("String formatting cannot fail");
        writeln!(
            output,
            "  return decodeFrame({:?}, bytes) as {}",
            message.type_name, message.type_name
        )
        .expect("String formatting cannot fail");
        output.push_str("}\n\n");
    }
}

fn typescript_type(name: &str) -> &str {
    match name {
        "u8" | "u16" | "u32" => "number",
        "u64" | "u128" => "bigint",
        other => other,
    }
}

fn comma_bytes(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(", ")
}

fn hex_bytes(bytes: &[u8]) -> String {
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(output, "{byte:02x}").expect("String formatting cannot fail");
    }
    output
}

const TYPESCRIPT_RUNTIME: &str = r#"export class ContractCodecError extends Error {
  override readonly name = "ContractCodecError"
}

export const FRAME_HEADER_BYTES = 28
const MAX_U64 = (1n << 64n) - 1n
const MAX_U128 = (1n << 128n) - 1n

function reject(message: string): never {
  throw new ContractCodecError(message)
}

function asRecord(value: unknown, context: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || INTRINSIC_ARRAY_IS_ARRAY(value)) {
    reject(`${context} must be a plain object`)
  }
  if (INTRINSIC_OBJECT_GET_PROTOTYPE_OF(value) !== INTRINSIC_OBJECT_PROTOTYPE) {
    reject(`${context} must have the ordinary object prototype`)
  }
  return value as Record<string, unknown>
}

function snapshotExactDataFields(value: unknown, expected: readonly string[], context: string): Record<string, unknown> {
  const record = asRecord(value, context)
  const actual = INTRINSIC_REFLECT_OWN_KEYS(record)
  if (actual.length !== expected.length) reject(`${context} has missing or unknown fields`)
  for (let actualIndex = 0; actualIndex < actual.length; actualIndex += 1) {
    const key = actual[actualIndex]
    if (typeof key !== "string") reject(`${context} has missing or unknown fields`)
    let found = false
    for (let expectedIndex = 0; expectedIndex < expected.length; expectedIndex += 1) {
      if (expected[expectedIndex] === key) {
        found = true
        break
      }
    }
    if (!found) reject(`${context} has missing or unknown fields`)
  }
  const snapshot = INTRINSIC_OBJECT_CREATE(null) as Record<string, unknown>
  for (let index = 0; index < expected.length; index += 1) {
    const field = expected[index]!
    const descriptor = INTRINSIC_OBJECT_GET_OWN_PROPERTY_DESCRIPTOR(record, field)
    if (!descriptor || !descriptor.enumerable || !("value" in descriptor)) {
      reject(`${context}.${field} must be an enumerable data property`)
    }
    snapshot[field] = descriptor.value
  }
  return snapshot
}

function asUnsigned(value: unknown, maximum: bigint, context: string): bigint {
  if (typeof value !== "bigint" || value < 0n || value > maximum) reject(`${context} is outside its canonical unsigned range`)
  return value
}

function snapshotByteArray(value: unknown, expectedLength: number | undefined, context: string): Uint8Array {
  if (typeof value !== "object" || value === null || !INTRINSIC_TYPED_ARRAY_LENGTH || !INTRINSIC_TYPED_ARRAY_TAG) {
    reject(expectedLength === undefined ? `${context} must be Uint8Array` : `${context} must be exactly ${expectedLength} opaque bytes`)
  }
  let actualLength: number
  try {
    const tag = INTRINSIC_REFLECT_APPLY(INTRINSIC_TYPED_ARRAY_TAG, value, []) as string
    if (tag !== "Uint8Array") reject(`${context} must be Uint8Array`)
    actualLength = INTRINSIC_REFLECT_APPLY(INTRINSIC_TYPED_ARRAY_LENGTH, value, []) as number
  } catch {
    reject(expectedLength === undefined ? `${context} must be Uint8Array` : `${context} must be exactly ${expectedLength} opaque bytes`)
  }
  if (expectedLength !== undefined && actualLength !== expectedLength) {
    reject(`${context} must be exactly ${expectedLength} opaque bytes`)
  }
  const snapshot = new INTRINSIC_UINT8_ARRAY(actualLength)
  try {
    INTRINSIC_REFLECT_APPLY(INTRINSIC_UINT8_ARRAY_SET, snapshot, [value])
  } catch {
    reject(expectedLength === undefined ? `${context} must be Uint8Array` : `${context} must be exactly ${expectedLength} opaque bytes`)
  }
  return snapshot
}

function isZeroBytes(value: unknown): boolean {
  if (typeof value !== "object" || value === null || !INTRINSIC_TYPED_ARRAY_LENGTH || !INTRINSIC_TYPED_ARRAY_TAG) return true
  let length: number
  try {
    if (INTRINSIC_REFLECT_APPLY(INTRINSIC_TYPED_ARRAY_TAG, value, []) !== "Uint8Array") return true
    length = INTRINSIC_REFLECT_APPLY(INTRINSIC_TYPED_ARRAY_LENGTH, value, []) as number
  } catch {
    return true
  }
  let aggregate = 0
  const bytes = value as Uint8Array
  for (let index = 0; index < length; index += 1) aggregate |= bytes[index]!
  return aggregate === 0
}

function fieldNames(fields: readonly RuntimeField[]): string[] {
  const names: string[] = []
  for (let index = 0; index < fields.length; index += 1) names[index] = fields[index]!.name
  return names
}

function variantNamed(variants: readonly RuntimeVariant[], name: unknown): RuntimeVariant | undefined {
  for (let index = 0; index < variants.length; index += 1) {
    const variant = variants[index]!
    if (variant.name === name) return variant
  }
  return undefined
}

function variantTagged(variants: readonly RuntimeVariant[], tag: number): RuntimeVariant | undefined {
  for (let index = 0; index < variants.length; index += 1) {
    const variant = variants[index]!
    if (variant.tag === tag) return variant
  }
  return undefined
}

function matchesConstantBytes(actual: Uint8Array, expected: readonly number[]): boolean {
  if (actual.length !== expected.length) return false
  for (let index = 0; index < expected.length; index += 1) {
    if (actual[index] !== expected[index]) return false
  }
  return true
}

function snapshotStructFields(
  value: unknown,
  fields: readonly RuntimeField[],
  context: string,
): Record<string, unknown> {
  const snapshot = snapshotExactDataFields(value, fieldNames(fields), context)
  for (let index = 0; index < fields.length; index += 1) {
    const field = fields[index]!
    const descriptor = CODEC_TYPE_DESCRIPTORS[field.typeName]
    if (descriptor?.kind === "fixedBytes") {
      snapshot[field.name] = snapshotByteArray(snapshot[field.name], descriptor.length, field.name)
    }
  }
  return snapshot
}

function validateRules(value: Record<string, unknown>, rules: readonly RuntimeRule[], ignoredField?: string): void {
  for (let index = 0; index < rules.length; index += 1) {
    const rule = rules[index]!
    if (
      ((rule.kind === "nonZeroU64" || rule.kind === "nonZeroBytes") && rule.field === ignoredField) ||
      ((rule.kind === "lessThanU64" || rule.kind === "maxSpanU64") && rule.lower === ignoredField)
    ) continue
    switch (rule.kind) {
      case "nonZeroU64":
        if (asUnsigned(value[rule.field], MAX_U64, rule.field) === 0n) reject(`${rule.field} must be non-zero`)
        break
      case "nonZeroBytes":
        if (isZeroBytes(value[rule.field])) reject(`${rule.field} must not be all-zero bytes`)
        break
      case "lessThanU64": {
        const lower = asUnsigned(value[rule.lower], MAX_U64, rule.lower)
        const upper = asUnsigned(value[rule.upper], MAX_U64, rule.upper)
        if (lower >= upper) reject(`${rule.lower} must be less than ${rule.upper}`)
        break
      }
      case "maxSpanU64": {
        const lower = asUnsigned(value[rule.lower], MAX_U64, rule.lower)
        const upper = asUnsigned(value[rule.upper], MAX_U64, rule.upper)
        if (upper < lower || upper - lower > rule.maximum) reject(`${rule.upper} exceeds its maximum canonical span`)
        break
      }
    }
  }
}

class Writer {
  private readonly bytes: number[] = []

  private append(value: number): void {
    this.bytes[this.bytes.length] = value
  }

  writeBytes(bytes: Uint8Array | readonly number[]): void {
    for (let index = 0; index < bytes.length; index += 1) this.append(bytes[index]!)
  }

  writeU8(value: number): void {
    if (!INTRINSIC_NUMBER_IS_INTEGER(value) || value < 0 || value > 0xff) reject("u8 is outside its canonical range")
    this.append(value)
  }

  writeU16(value: number): void {
    if (!INTRINSIC_NUMBER_IS_INTEGER(value) || value < 0 || value > 0xffff) reject("u16 is outside its canonical range")
    this.append(value & 0xff)
    this.append((value >>> 8) & 0xff)
  }

  writeU32(value: number): void {
    if (!INTRINSIC_NUMBER_IS_INTEGER(value) || value < 0 || value > 0xffff_ffff) reject("u32 is outside its canonical range")
    this.append(value & 0xff)
    this.append((value >>> 8) & 0xff)
    this.append((value >>> 16) & 0xff)
    this.append((value >>> 24) & 0xff)
  }

  writeBigInt(value: bigint, width: number): void {
    let remaining = value
    for (let index = 0; index < width; index += 1) {
      this.append(INTRINSIC_NUMBER(remaining & 0xffn))
      remaining >>= 8n
    }
  }

  finish(): Uint8Array {
    const snapshot = new INTRINSIC_UINT8_ARRAY(this.bytes.length)
    for (let index = 0; index < this.bytes.length; index += 1) snapshot[index] = this.bytes[index]!
    return snapshot
  }
}

class Reader {
  private offset = 0

  constructor(private readonly bytes: Uint8Array) {}

  remaining(): number {
    return this.bytes.length - this.offset
  }

  readBytes(length: number): Uint8Array {
    if (!INTRINSIC_NUMBER_IS_SAFE_INTEGER(length) || length < 0 || length > this.remaining()) reject("truncated message")
    const start = this.offset
    this.offset += length
    const snapshot = new INTRINSIC_UINT8_ARRAY(length)
    for (let index = 0; index < length; index += 1) snapshot[index] = this.bytes[start + index]!
    return snapshot
  }

  readU8(): number {
    return this.readBytes(1)[0]!
  }

  readU16(): number {
    const bytes = this.readBytes(2)
    return bytes[0]! | (bytes[1]! << 8)
  }

  readU32(): number {
    const bytes = this.readBytes(4)
    return (bytes[0]! | (bytes[1]! << 8) | (bytes[2]! << 16) | (bytes[3]! << 24)) >>> 0
  }

  readBigInt(width: number): bigint {
    const bytes = this.readBytes(width)
    let value = 0n
    for (let index = bytes.length - 1; index >= 0; index -= 1) value = (value << 8n) | INTRINSIC_BIGINT(bytes[index]!)
    return value
  }

  finish(): void {
    if (this.remaining() !== 0) reject("trailing message bytes")
  }
}

function encodeValue(typeName: string, value: unknown, writer: Writer, byteSnapshot = false): void {
  if (typeName === "u64") {
    writer.writeBigInt(asUnsigned(value, MAX_U64, "u64"), 8)
    return
  }
  if (typeName === "u128") {
    writer.writeBigInt(asUnsigned(value, MAX_U128, "u128"), 16)
    return
  }

  const descriptor = CODEC_TYPE_DESCRIPTORS[typeName]
  if (!descriptor) reject(`unknown schema type ${typeName}`)
  switch (descriptor.kind) {
    case "id128": {
      const id = asUnsigned(value, MAX_U128, typeName)
      if (id === 0n) reject(`${typeName} must be non-zero`)
      writer.writeBigInt(id, 16)
      break
    }
    case "fixedBytes":
      writer.writeBytes(byteSnapshot ? (value as Uint8Array) : snapshotByteArray(value, descriptor.length, typeName))
      break
    case "unit": {
      snapshotExactDataFields(value, [], typeName)
      break
    }
    case "struct": {
      const record = snapshotStructFields(value, descriptor.fields, typeName)
      validateRules(record, descriptor.rules)
      for (let index = 0; index < descriptor.fields.length; index += 1) {
        const field = descriptor.fields[index]!
        const fieldDescriptor = CODEC_TYPE_DESCRIPTORS[field.typeName]
        encodeValue(field.typeName, record[field.name], writer, fieldDescriptor?.kind === "fixedBytes")
      }
      break
    }
    case "enum": {
      const variant = variantNamed(descriptor.variants, value)
      if (!variant) reject(`unknown ${typeName} variant`)
      writer.writeU8(variant.tag)
      break
    }
    case "union": {
      const record = snapshotExactDataFields(value, ["tag", "value"], typeName)
      const variant = variantNamed(descriptor.variants, record.tag)
      if (!variant?.payloadType) reject(`unknown ${typeName} variant`)
      writer.writeU8(variant.tag)
      encodeValue(variant.payloadType, record.value, writer)
      break
    }
  }
}

function decodeValue(typeName: string, reader: Reader): unknown {
  if (typeName === "u64") return reader.readBigInt(8)
  if (typeName === "u128") return reader.readBigInt(16)

  const descriptor = CODEC_TYPE_DESCRIPTORS[typeName]
  if (!descriptor) reject(`unknown schema type ${typeName}`)
  switch (descriptor.kind) {
    case "id128": {
      const id = reader.readBigInt(16)
      if (id === 0n) reject(`${typeName} must be non-zero`)
      return id
    }
    case "fixedBytes":
      return reader.readBytes(descriptor.length)
    case "unit":
      return {}
    case "struct": {
      const value: Record<string, unknown> = {}
      for (let index = 0; index < descriptor.fields.length; index += 1) {
        const field = descriptor.fields[index]!
        INTRINSIC_OBJECT_DEFINE_PROPERTY(value, field.name, {
          configurable: true,
          enumerable: true,
          value: decodeValue(field.typeName, reader),
          writable: true,
        })
      }
      validateRules(value, descriptor.rules)
      return value
    }
    case "enum": {
      const tag = reader.readU8()
      const variant = variantTagged(descriptor.variants, tag)
      if (!variant) reject(`unknown ${typeName} variant tag ${tag}`)
      return variant.name
    }
    case "union": {
      const tag = reader.readU8()
      const variant = variantTagged(descriptor.variants, tag)
      if (!variant?.payloadType) reject(`unknown ${typeName} variant tag ${tag}`)
      const value: Record<string, unknown> = {}
      INTRINSIC_OBJECT_DEFINE_PROPERTY(value, "tag", {
        configurable: true,
        enumerable: true,
        value: variant.name,
        writable: true,
      })
      INTRINSIC_OBJECT_DEFINE_PROPERTY(value, "value", {
        configurable: true,
        enumerable: true,
        value: decodeValue(variant.payloadType, reader),
        writable: true,
      })
      return value
    }
  }
}

function messageNameForTag(tag: number): string | undefined {
  for (let index = 0; index < CODEC_MESSAGE_TAG_ENTRIES.length; index += 1) {
    const entry = CODEC_MESSAGE_TAG_ENTRIES[index]!
    if (entry[1] === tag) return entry[0]
  }
  return undefined
}

function encodeFrame(typeName: keyof typeof CODEC_MESSAGE_TAGS, value: unknown): Uint8Array {
  const payloadWriter = new Writer()
  encodeValue(typeName, value, payloadWriter)
  const payload = payloadWriter.finish()
  const total = FRAME_HEADER_BYTES + payload.length
  if (total > MAX_MESSAGE_BYTES) reject(`message is ${total} bytes; maximum is ${MAX_MESSAGE_BYTES}`)

  const writer = new Writer()
  writer.writeBytes(CODEC_MESSAGE_MAGIC)
  writer.writeU16(PROTOCOL_VERSION)
  writer.writeBytes(CODEC_SCHEMA_FINGERPRINT)
  writer.writeU16(CODEC_MESSAGE_TAGS[typeName])
  writer.writeU32(payload.length)
  writer.writeBytes(payload)
  return writer.finish()
}

export interface FrameHeader {
  readonly messageName: string
  readonly payloadLength: number
  /** Header plus payload. What a reader has to have before it may decode. */
  readonly frameLength: number
}

/**
 * Read a fixed-width frame header, and check it before anything follows it.
 *
 * Exported because a peer reading frames off a pipe has to know where one ends
 * before it can hand the bytes to a decoder, and the alternative is that it
 * works the length out itself. Two answers to "how long is this frame" is one
 * more than a boundary can hold. `decodeFrame` uses it too, so the two cannot
 * drift.
 */
export function decodeFrameHeader(bytes: Uint8Array): FrameHeader {
  const header = snapshotByteArray(bytes, FRAME_HEADER_BYTES, "frame header")
  const reader = new Reader(header)
  const magic = reader.readBytes(CODEC_MESSAGE_MAGIC.length)
  if (!matchesConstantBytes(magic, CODEC_MESSAGE_MAGIC)) reject("invalid message magic")
  const version = reader.readU16()
  if (version !== PROTOCOL_VERSION) reject(`unsupported protocol version ${version}`)
  const fingerprint = reader.readBytes(CODEC_SCHEMA_FINGERPRINT.length)
  if (!matchesConstantBytes(fingerprint, CODEC_SCHEMA_FINGERPRINT)) reject("schema fingerprint mismatch")
  const tag = reader.readU16()
  const messageName = messageNameForTag(tag)
  if (!messageName) reject(`unknown message tag ${tag}`)
  const payloadLength = reader.readU32()
  const frameLength = FRAME_HEADER_BYTES + payloadLength
  if (frameLength > MAX_MESSAGE_BYTES) reject("oversize payload length")
  reader.finish()
  return { messageName, payloadLength, frameLength }
}

/**
 * A fixed label, widened to a digest. The mirror of `label_digest` in the
 * schema, and generated from the same declaration so the two stay one rule.
 *
 * Not a hash. These fields are opaque identifiers, and one that is legible in a
 * hex dump is more use to whoever is reading a ledger than one that is not.
 * Labels longer than 31 bytes are truncated, so they must be distinct within
 * that length.
 */
export function labelDigest(text: string): Digest {
  const bytes = new Uint8Array(32)
  const width = text.length < 31 ? text.length : 31
  for (let index = 0; index < width; index += 1) {
    const code = text.charCodeAt(index)
    if (code > 0x7f) reject("a label is ASCII")
    bytes[index] = code
  }
  bytes[31] = 1
  return bytes as Digest
}

function decodeFrame(typeName: keyof typeof CODEC_MESSAGE_TAGS, bytes: Uint8Array): unknown {
  const message = snapshotByteArray(bytes, undefined, "message")
  if (message.length > MAX_MESSAGE_BYTES) reject(`message is ${message.length} bytes; maximum is ${MAX_MESSAGE_BYTES}`)
  if (message.length < FRAME_HEADER_BYTES) reject("truncated message")
  const header = decodeFrameHeader(message.subarray(0, FRAME_HEADER_BYTES))
  if (header.messageName !== typeName) reject(`expected ${typeName}, received ${header.messageName}`)
  if (message.length < header.frameLength) reject("truncated message")
  if (message.length > header.frameLength) reject("trailing message bytes")
  const payloadReader = new Reader(message.subarray(FRAME_HEADER_BYTES, header.frameLength))
  const decoded = decodeValue(typeName, payloadReader)
  payloadReader.finish()
  return decoded
}

function snapshotTrustReceiptIntegrity(value: TrustReceipt): {
  readonly bytes: Uint8Array
  readonly expectedDigest: Digest
} {
  const descriptor = CODEC_TYPE_DESCRIPTORS.TrustReceipt
  if (!descriptor || descriptor.kind !== "struct" || !descriptor.integrityField) reject("TrustReceipt schema is unavailable")
  const record = snapshotStructFields(value, descriptor.fields, "TrustReceipt")
  validateRules(record, descriptor.rules, descriptor.integrityField)
  const writer = new Writer()
  writer.writeBytes(CODEC_TRUST_INTEGRITY_DOMAIN)
  for (let index = 0; index < descriptor.fields.length; index += 1) {
    const field = descriptor.fields[index]!
    if (field.name !== descriptor.integrityField) {
      const fieldDescriptor = CODEC_TYPE_DESCRIPTORS[field.typeName]
      encodeValue(field.typeName, record[field.name], writer, fieldDescriptor?.kind === "fixedBytes")
    }
  }
  return { bytes: writer.finish(), expectedDigest: record[descriptor.integrityField] as Digest }
}

export function canonicalTrustReceiptIntegrityBytes(value: TrustReceipt): Uint8Array {
  return snapshotTrustReceiptIntegrity(value).bytes
}


"#;
