import { describe, expect, test } from "bun:test"
import {
  CANCEL_COMMAND_FIXTURE_PATH,
  CANCEL_COMMAND_MANIFEST_PATH,
  GENERATED_CONTRACTS_PATH,
  generateContractBundle,
  synchronizeGeneratedContracts,
} from "../scripts/contracts"
import {
  CONTRACT_DESCRIPTOR,
  ContractCodecError,
  MAX_MESSAGE_BYTES,
  MESSAGE_MAGIC,
  MESSAGE_TAGS,
  PROTOCOL_VERSION,
  SCHEMA_FINGERPRINT,
  TRUST_INTEGRITY_DOMAIN,
  canonicalTrustReceiptIntegrityBytes,
  decodeAdmissionEvent,
  decodeCommand,
  decodeUnverifiedTrustReceipt,
  encodeAdmissionEvent,
  encodeCommand,
  encodeUnverifiedTrustReceipt,
  type AdmissionEvent,
  type ArtifactHandle,
  type BootId,
  type CatalogHandle,
  type Command,
  type CommandId,
  type Digest,
  type EventId,
  type KernelSessionId,
  type Nonce,
  type PolicyHandle,
  type ProposalId,
  type ReceiptId,
  type RunId,
  type StateHandle,
  type UnverifiedTrustReceipt,
} from "../src/contracts"
import * as contractModule from "../src/contracts"

describe("S104 generated TypeScript contracts", () => {
  test("the Rust generator is the byte-for-byte source of the read-only artifact", async () => {
    const canonical = new Uint8Array(await Bun.file(GENERATED_CONTRACTS_PATH).arrayBuffer())
    const fixture = new Uint8Array(await Bun.file(CANCEL_COMMAND_FIXTURE_PATH).arrayBuffer())
    const manifest = new Uint8Array(await Bun.file(CANCEL_COMMAND_MANIFEST_PATH).arrayBuffer())
    const generated = await generateContractBundle()
    expect(generated.contracts).toEqual(canonical)
    expect(generated.cancelCommandFixture).toEqual(fixture)
    expect(generated.cancelCommandManifest).toEqual(manifest)
    expect(
      new TextDecoder().decode(canonical).startsWith("// @generated by abdo-contracts-codegen; DO NOT EDIT.\n"),
    ).toBeTrue()
    expect(new TextDecoder().decode(canonical)).toContain("Source of truth: crates/abdo-contracts/src/schema.rs")
    expect(await synchronizeGeneratedContracts("check")).toEqual({
      mode: "check",
      byteLength: canonical.byteLength,
      fixtureByteLength: fixture.byteLength,
      manifestByteLength: manifest.byteLength,
    })
  }, 30_000)

  test("one Rust-authored Cancel fixture proves byte and decoded-shape parity", async () => {
    const fixture = new Uint8Array(await Bun.file(CANCEL_COMMAND_FIXTURE_PATH).arrayBuffer())
    const manifest = requireRecord(JSON.parse(await Bun.file(CANCEL_COMMAND_MANIFEST_PATH).text()), "fixture manifest")
    const shape = requireRecord(manifest.shape, "fixture shape")

    expect(manifest._diagnostic_only).toBeTrue()
    expect(manifest.message).toBe("Command.Cancel")
    expect(manifest.protocol_version).toBe(PROTOCOL_VERSION)
    expect(manifest.frame_length).toBe(fixture.byteLength)
    expect(manifest.frame_hex).toBe(hex(fixture))
    expect(manifest.schema_fingerprint_hex).toBe(hex(SCHEMA_FINGERPRINT))

    const decoded = decodeCommand(fixture)
    expect(normalizeCancelCommand(decoded)).toEqual({
      tag: requiredString(shape, "tag"),
      command_id: requiredString(shape, "command_id"),
      cancellation_id: requiredString(shape, "cancellation_id"),
      proposal_id: requiredString(shape, "proposal_id"),
      scope: requiredString(shape, "scope"),
      cause: requiredString(shape, "cause"),
      requested_at_ms: requiredString(shape, "requested_at_ms"),
    })
    expect(encodeCommand(decoded)).toEqual(fixture)
  })

  test("decoder fields bypass inherited setters and preserve the exact fixture", async () => {
    const fixture = new Uint8Array(await Bun.file(CANCEL_COMMAND_FIXTURE_PATH).arrayBuffer())
    const intrinsicDefineProperty = Object.defineProperty
    const inheritedKeys = ["command_id", "tag", "value"] as const
    const inheritedDescriptors = inheritedKeys.map((key) => Object.getOwnPropertyDescriptor(Object.prototype, key))
    let setterCalls = 0
    let roundTrip: Uint8Array | undefined
    let ownsDecodedFields = false
    let preservesOrdinaryPrototype = false
    let failure: unknown

    try {
      for (let index = 0; index < inheritedKeys.length; index += 1) {
        intrinsicDefineProperty(Object.prototype, inheritedKeys[index]!, {
          configurable: true,
          set: () => {
            setterCalls += 1
          },
        })
      }

      const decoded = decodeCommand(fixture)
      const payload = Object.getOwnPropertyDescriptor(decoded, "value")?.value as Record<string, unknown> | undefined
      ownsDecodedFields =
        Object.getOwnPropertyDescriptor(decoded, "tag")?.value === "Cancel" &&
        payload !== undefined &&
        Object.getOwnPropertyDescriptor(payload, "command_id") !== undefined
      preservesOrdinaryPrototype =
        payload !== undefined &&
        Object.getPrototypeOf(decoded) === Object.prototype &&
        Object.getPrototypeOf(payload) === Object.prototype
      roundTrip = encodeCommand(decoded)
    } catch (error) {
      failure = error
    } finally {
      for (let index = inheritedKeys.length - 1; index >= 0; index -= 1) {
        const key = inheritedKeys[index]!
        const descriptor = inheritedDescriptors[index]
        if (descriptor) intrinsicDefineProperty(Object.prototype, key, descriptor)
        else Reflect.deleteProperty(Object.prototype, key)
      }
    }

    expect(failure).toBeUndefined()
    expect(setterCalls).toBe(0)
    expect(ownsDecodedFields).toBeTrue()
    expect(preservesOrdinaryPrototype).toBeTrue()
    expect(roundTrip).toEqual(fixture)
  })

  test("public snapshots cannot mutate codec bytes, tags or nested descriptor rules", async () => {
    const fixture = new Uint8Array(await Bun.file(CANCEL_COMMAND_FIXTURE_PATH).arrayBuffer())
    const decoded = decodeCommand(fixture)
    const receipt = validTrustReceipt()
    const canonicalIntegrity = canonicalTrustReceiptIntegrityBytes(receipt.receipt)
    const originalMagic = MESSAGE_MAGIC.slice()
    const originalFingerprint = SCHEMA_FINGERPRINT.slice()
    const originalIntegrityDomain = TRUST_INTEGRITY_DOMAIN.slice()

    try {
      MESSAGE_MAGIC.fill(0)
      SCHEMA_FINGERPRINT.fill(0)
      TRUST_INTEGRITY_DOMAIN.fill(0)

      expect(Reflect.set(MESSAGE_TAGS, "Command", 99)).toBeFalse()
      expect(Reflect.set(CONTRACT_DESCRIPTOR, "version", 99)).toBeFalse()
      expect(Reflect.set(CONTRACT_DESCRIPTOR.magic, 0, 0)).toBeFalse()
      expect(Reflect.set(CONTRACT_DESCRIPTOR.schemaFingerprint, 0, 0)).toBeFalse()
      expect(Reflect.set(CONTRACT_DESCRIPTOR.trustIntegrityDomain, 0, 0)).toBeFalse()
      expect(Reflect.set(CONTRACT_DESCRIPTOR.messages, "Command", 99)).toBeFalse()

      const proposed = CONTRACT_DESCRIPTOR.types.ProposedIntent
      if (!proposed || proposed.kind !== "struct") throw new Error("ProposedIntent descriptor is not a struct")
      expect(Reflect.set(proposed.fields[0]!, "name", "forged_field")).toBeFalse()
      expect(Reflect.set(proposed.rules[0]!, "field", "forged_rule")).toBeFalse()

      const command = CONTRACT_DESCRIPTOR.types.Command
      if (!command || command.kind !== "union") throw new Error("Command descriptor is not a union")
      expect(Reflect.set(command.variants[0]!, "tag", 99)).toBeFalse()

      expect(decodeCommand(fixture)).toEqual(decoded)
      expect(encodeCommand(decoded)).toEqual(fixture)
      expect(canonicalTrustReceiptIntegrityBytes(receipt.receipt)).toEqual(canonicalIntegrity)
    } finally {
      MESSAGE_MAGIC.set(originalMagic)
      SCHEMA_FINGERPRINT.set(originalFingerprint)
      TRUST_INTEGRITY_DOMAIN.set(originalIntegrityDomain)
    }
  })

  test("descriptor fixes framing, message tags and opaque policy/catalog authority inputs", () => {
    expect([...MESSAGE_MAGIC]).toEqual([65, 66, 68, 67])
    expect(PROTOCOL_VERSION).toBe(1)
    expect(MESSAGE_TAGS).toEqual({
      Command: 1,
      AdmissionEvent: 2,
      UnverifiedTrustReceipt: 3,
      InputEnvelope: 4,
      ToolSpec: 5,
      EnforcementReport: 6,
      SurfaceObservation: 7,
      SurfaceAction: 8,
      SurfaceReceipt: 9,
      EffectRequest: 10,
      EffectOutcome: 11,
    })
    expect(TRUST_INTEGRITY_DOMAIN.at(-1)).toBe(0)
    expect(CONTRACT_DESCRIPTOR).toMatchObject({
      name: "abdo-kernel-contracts",
      version: 1,
      magic: [65, 66, 68, 67],
      maxMessageBytes: 65_536,
      schemaFingerprint: [...SCHEMA_FINGERPRINT],
    })

    const proposed = CONTRACT_DESCRIPTOR.types.ProposedIntent
    expect(proposed?.kind).toBe("struct")
    if (!proposed || proposed.kind !== "struct") throw new Error("ProposedIntent descriptor is not a struct")
    const fields: readonly string[] = proposed.fields.map((field) => field.name)
    for (const required of [
      "state",
      "state_digest",
      "policy",
      "policy_digest",
      "catalog",
      "catalog_digest",
      "trust_receipt_digest",
    ]) {
      expect(fields).toContain(required)
    }
    expect(fields.some((field) => /(?:raw|content|text|secret)/i.test(field))).toBeFalse()
  })

  test("Command framing is little-endian, round-trips exactly and rejects every frame mutation", () => {
    const command = validCommand()
    const frame = encodeCommand(command)
    const header = new DataView(frame.buffer, frame.byteOffset, frame.byteLength)
    expect(frame.slice(0, 4)).toEqual(new Uint8Array([65, 66, 68, 67]))
    expect(header.getUint16(4, true)).toBe(1)
    expect(hex(frame.slice(6, 22))).toBe(hex(SCHEMA_FINGERPRINT))
    expect(header.getUint16(22, true)).toBe(1)
    expect(header.getUint32(24, true)).toBe(frame.byteLength - 28)
    expect(decodeCommand(frame)).toEqual(command)

    for (const mutation of [
      { bytes: replaceByte(frame, 0, 0), message: "invalid message magic" },
      { bytes: replaceU16(frame, 4, 2), message: "unsupported protocol version" },
      { bytes: replaceByte(frame, 6, SCHEMA_FINGERPRINT[0]! ^ 0xff), message: "schema fingerprint mismatch" },
      { bytes: replaceU16(frame, 22, 99), message: "unknown message tag" },
      { bytes: replaceU16(frame, 22, 2), message: "expected Command" },
      { bytes: replaceU32(frame, 24, frame.byteLength), message: "truncated message" },
      { bytes: replaceU32(frame, 24, frame.byteLength - 29), message: "trailing message bytes" },
      { bytes: frame.slice(0, -1), message: "truncated message" },
      { bytes: Uint8Array.from([...frame, 1]), message: "trailing message bytes" },
      { bytes: replaceByte(frame, 28, 99), message: "unknown Command variant" },
    ]) {
      expect(() => decodeCommand(mutation.bytes)).toThrow(mutation.message)
    }

    const zeroCommandId = frame.slice()
    zeroCommandId.fill(0, 29, 45)
    expect(() => decodeCommand(zeroCommandId)).toThrow("CommandId must be non-zero")
    expect(() => decodeCommand(new Uint8Array(MAX_MESSAGE_BYTES + 1))).toThrow("maximum")
  })

  test("encoders reject extra shape, raw policy content, zero handles and invalid time ordering", () => {
    const command = validCommand()
    expect(() => encodeCommand(asCommand({ ...command, unexpected: true }))).toThrow("missing or unknown fields")
    expect(() =>
      encodeCommand(
        asCommand({
          ...command,
          value: { ...command.value, intent: { ...command.value.intent, policy: "raw policy text" } },
        }),
      ),
    ).toThrow("policy must be exactly 32 opaque bytes")
    expect(() =>
      encodeCommand({
        ...command,
        value: { ...command.value, intent: { ...command.value.intent, catalog: opaque<CatalogHandle>(0) } },
      }),
    ).toThrow("catalog must not be all-zero bytes")
    expect(() =>
      encodeCommand({
        ...command,
        value: {
          ...command.value,
          intent: { ...command.value.intent, requested_at_ms: command.value.intent.expires_at_ms },
        },
      }),
    ).toThrow("requested_at_ms must be less than expires_at_ms")
  })

  test("encoders reject accessors, hidden keys, symbols and exotic object prototypes without invoking getters", () => {
    const accessorCommand = validCommand()
    let getterCalls = 0
    Object.defineProperty(accessorCommand.value.intent, "requested_at_ms", {
      enumerable: true,
      get() {
        getterCalls += 1
        return getterCalls === 1 ? 1_000n : 2_000n
      },
    })
    expect(() => encodeCommand(accessorCommand)).toThrow(ContractCodecError)
    expect(getterCalls).toBe(0)

    const symbolExtra = validCommand()
    Object.defineProperty(symbolExtra, Symbol("forged"), { enumerable: true, value: true })
    expect(() => encodeCommand(symbolExtra)).toThrow(ContractCodecError)

    const hiddenExtra = validCommand()
    Object.defineProperty(hiddenExtra, "forged", { enumerable: false, value: true })
    expect(() => encodeCommand(hiddenExtra)).toThrow(ContractCodecError)

    const exoticPrototype = validCommand()
    Object.setPrototypeOf(exoticPrototype, { forged: true })
    expect(() => encodeCommand(exoticPrototype)).toThrow(ContractCodecError)
  })

  test("typed-array subclasses cannot forge opaque bytes or decoder frames through iterators and slice", async () => {
    class IteratorForgingBytes extends Uint8Array {
      override [Symbol.iterator]() {
        return new Uint8Array(this.length).fill(1)[Symbol.iterator]()
      }
    }

    const command = validCommand()
    expect(() =>
      encodeCommand(
        asCommand({
          ...command,
          value: { ...command.value, intent: { ...command.value.intent, policy: new IteratorForgingBytes(32) } },
        }),
      ),
    ).toThrow("policy must not be all-zero bytes")

    const fixture = new Uint8Array(await Bun.file(CANCEL_COMMAND_FIXTURE_PATH).arrayBuffer())
    const shadowFrame = new (class extends Uint8Array {})(fixture.length)
    Object.defineProperty(shadowFrame, "slice", { value: () => fixture.slice() })
    expect(() => decodeCommand(shadowFrame)).toThrow("invalid message magic")

    const wrongTypedArray = new Uint16Array(Math.ceil(fixture.byteLength / Uint16Array.BYTES_PER_ELEMENT))
    // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
    expect(() => decodeCommand(wrongTypedArray as unknown as Uint8Array)).toThrow("message must be Uint8Array")
  })

  test("captured codec intrinsics ignore after-import monkeypatches", () => {
    const intrinsicDefineProperty = Object.defineProperty
    const command = validCommand()
    const receipt = validTrustReceipt()
    const expectedFrame = encodeCommand(command)
    const expectedDecoded = decodeCommand(expectedFrame)
    const expectedIntegrity = canonicalTrustReceiptIntegrityBytes(receipt.receipt)
    const targets: readonly (readonly [object, PropertyKey])[] = [
      [Uint8Array.prototype, "some"],
      [Uint8Array.prototype, "slice"],
      [Uint8Array.prototype, "set"],
      [Array.prototype, "push"],
      [Array.prototype, "find"],
      [Array.prototype, "map"],
      [Array.prototype, "some"],
      [Array.prototype, "includes"],
      [Array.prototype, Symbol.iterator],
      [Object, "entries"],
      [Object, "defineProperty"],
      [Object, "getPrototypeOf"],
      [Object, "getOwnPropertyDescriptor"],
      [Reflect, "ownKeys"],
      [Array, "isArray"],
    ]
    const descriptors = targets.map(([target, key]) => Object.getOwnPropertyDescriptor(target, key))

    let poisonCalls = 0
    const poison = () => {
      poisonCalls += 1
      throw new Error("monkeypatched intrinsic was called")
    }
    let actualFrame: Uint8Array | undefined
    let actualDecoded: Command | undefined
    let actualIntegrity: Uint8Array | undefined
    let failure: unknown
    try {
      for (let index = 0; index < targets.length; index += 1) {
        const target = targets[index]![0]
        const key = targets[index]![1]
        const descriptor = descriptors[index]
        intrinsicDefineProperty(
          target,
          key,
          descriptor ? { ...descriptor, value: poison } : { configurable: true, value: poison, writable: true },
        )
      }
      actualFrame = encodeCommand(command)
      actualDecoded = decodeCommand(expectedFrame)
      actualIntegrity = canonicalTrustReceiptIntegrityBytes(receipt.receipt)
    } catch (error) {
      failure = error
    } finally {
      for (let index = targets.length - 1; index >= 0; index -= 1) {
        const target = targets[index]![0]
        const key = targets[index]![1]
        const descriptor = descriptors[index]
        if (descriptor) intrinsicDefineProperty(target, key, descriptor)
        else Reflect.deleteProperty(target, key)
      }
    }

    expect(failure).toBeUndefined()
    expect(poisonCalls).toBe(0)
    expect(actualFrame).toEqual(expectedFrame)
    expect(actualDecoded).toEqual(expectedDecoded)
    expect(actualIntegrity).toEqual(expectedIntegrity)
  })

  test("AdmissionEvent has its own strict message tag and exact decoded shape", () => {
    const event = validAdmissionEvent()
    const frame = encodeAdmissionEvent(event)
    expect(new DataView(frame.buffer, frame.byteOffset, frame.byteLength).getUint16(22, true)).toBe(2)
    expect(decodeAdmissionEvent(frame)).toEqual(event)
    expect(() => decodeCommand(frame)).toThrow("expected Command, received AdmissionEvent")
    expect(() => encodeAdmissionEvent(asAdmissionEvent({ ...event, value: { ...event.value, unknown: 1 } }))).toThrow(
      "missing or unknown fields",
    )
  })

  test("trust receipts remain unverified until a caller checks canonical integrity bytes", () => {
    const value = validTrustReceipt()
    const frame = encodeUnverifiedTrustReceipt(value)
    expect(new DataView(frame.buffer, frame.byteOffset, frame.byteLength).getUint16(22, true)).toBe(3)
    expect(decodeUnverifiedTrustReceipt(frame)).toEqual(value)

    const canonical = canonicalTrustReceiptIntegrityBytes(value.receipt)
    const changedDigest = {
      receipt: { ...value.receipt, integrity_digest: opaque<Digest>(99) },
    } satisfies UnverifiedTrustReceipt
    expect(canonicalTrustReceiptIntegrityBytes(changedDigest.receipt)).toEqual(canonical)

    // Every field other than the digest is part of what an authority seals, so
    // moving one must move the bytes.
    const movedGeneration = {
      receipt: { ...value.receipt, generation: value.receipt.generation + 1n },
    } satisfies UnverifiedTrustReceipt
    expect(canonicalTrustReceiptIntegrityBytes(movedGeneration.receipt)).not.toEqual(canonical)

    // And there is no verifier here to call. Deciding a receipt is good needs
    // the key that sealed it, which lives in the kernel; a generated function
    // that took a caller's closure and answered "verified" was handing out
    // authority this side does not have.
    for (const retired of ["verifyTrustReceiptIntegrity", "TrustReceiptIntegrityVerifier"]) {
      expect(Object.keys(contractModule)).not.toContain(retired)
    }
  })

  test("trust receipt decoder and TTL rules fail closed", () => {
    const value = validTrustReceipt()
    const frame = encodeUnverifiedTrustReceipt(value)
    expect(() => decodeUnverifiedTrustReceipt(replaceByte(frame, 28, 2))).toThrow("unknown ContractVersion variant")
    expect(() => decodeUnverifiedTrustReceipt(replaceByte(frame, 29, 2))).toThrow("unknown TrustDecision variant")

    const zeroNonce = frame.slice()
    zeroNonce.fill(0, 78, 110)
    expect(() => decodeUnverifiedTrustReceipt(zeroNonce)).toThrow("nonce must not be all-zero bytes")

    const excessiveTtl = {
      receipt: { ...value.receipt, expires_at_ms: value.receipt.issued_at_ms + 60_001n },
    } satisfies UnverifiedTrustReceipt
    expect(() => encodeUnverifiedTrustReceipt(excessiveTtl)).toThrow("expires_at_ms exceeds its maximum canonical span")
    expect(() => canonicalTrustReceiptIntegrityBytes(asTrustReceipt({ ...value.receipt, unexpected: true }))).toThrow(
      ContractCodecError,
    )
  })
})

type ProposeCommand = Extract<Command, { readonly tag: "Propose" }>
type ReceivedAdmissionEvent = Extract<AdmissionEvent, { readonly tag: "Received" }>

function validCommand(): ProposeCommand {
  return {
    tag: "Propose",
    value: {
      command_id: identifier<CommandId>(1),
      intent: {
        proposal_id: identifier<ProposalId>(2),
        scope: { tag: "Session", value: { kernel_session_id: identifier<KernelSessionId>(3) } },
        cause: { tag: "Root", value: {} },
        target: { kind: "Filesystem", claim_digest: opaque<Digest>(4) },
        operation_digest: opaque<Digest>(5),
        artifact: opaque<ArtifactHandle>(6),
        state: opaque<StateHandle>(7),
        state_digest: opaque<Digest>(8),
        policy: opaque<PolicyHandle>(9),
        policy_digest: opaque<Digest>(10),
        catalog: opaque<CatalogHandle>(11),
        catalog_digest: opaque<Digest>(12),
        trust_receipt_digest: opaque<Digest>(13),
        requested_at_ms: 1_000n,
        expires_at_ms: 2_000n,
      },
    },
  }
}

function validAdmissionEvent(): ReceivedAdmissionEvent {
  return {
    tag: "Received",
    value: {
      event_id: identifier<EventId>(14),
      proposal_id: identifier<ProposalId>(15),
      command_id: identifier<CommandId>(16),
      cause: { tag: "Command", value: { command_id: identifier<CommandId>(17) } },
      at_ms: 3_000n,
    },
  }
}

function validTrustReceipt(): UnverifiedTrustReceipt {
  return {
    receipt: {
      contract_version: "V1",
      decision: "Trusted",
      receipt_id: identifier<ReceiptId>(18),
      os_identity_digest: opaque<Digest>(19),
      nonce: opaque<Nonce>(20),
      boot_id: identifier<BootId>(21),
      run_id: identifier<RunId>(22),
      generation: 1n,
      source_digest: opaque<Digest>(23),
      entrypoint_digest: opaque<Digest>(24),
      issuer_digest: opaque<Digest>(25),
      artifact_digest: opaque<Digest>(26),
      trust_policy_digest: opaque<Digest>(27),
      reason_digest: opaque<Digest>(28),
      issued_at_ms: 10_000n,
      expires_at_ms: 69_999n,
      integrity_digest: opaque<Digest>(29),
    },
  }
}

// oxlint-disable-next-line typescript-eslint/no-unnecessary-type-parameters
function identifier<T extends bigint>(value: number): T {
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  return BigInt(value) as T
}

// oxlint-disable-next-line typescript-eslint/no-unnecessary-type-parameters
function opaque<T extends Uint8Array>(seed: number, length = 32): T {
  const bytes =
    seed === 0 ? new Uint8Array(length) : Uint8Array.from({ length }, (_, index) => (seed + index) % 255 || 1)
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  return bytes as T
}

function asCommand(value: unknown): Command {
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  return value as Command
}

function asAdmissionEvent(value: unknown): AdmissionEvent {
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  return value as AdmissionEvent
}

function asTrustReceipt(value: unknown): UnverifiedTrustReceipt["receipt"] {
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  return value as UnverifiedTrustReceipt["receipt"]
}

function replaceByte(source: Uint8Array, offset: number, value: number) {
  const changed = source.slice()
  changed[offset] = value
  return changed
}

function replaceU16(source: Uint8Array, offset: number, value: number) {
  const changed = source.slice()
  new DataView(changed.buffer, changed.byteOffset, changed.byteLength).setUint16(offset, value, true)
  return changed
}

function replaceU32(source: Uint8Array, offset: number, value: number) {
  const changed = source.slice()
  new DataView(changed.buffer, changed.byteOffset, changed.byteLength).setUint32(offset, value, true)
  return changed
}

function requireRecord(value: unknown, context: string): Record<string, unknown> {
  if (!isRecord(value)) throw new Error(`${context} must be an object`)
  return value
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value)
}

function requiredString(value: Record<string, unknown>, key: string) {
  const field = value[key]
  if (typeof field !== "string") throw new Error(`fixture ${key} must be a string`)
  return field
}

function hex(bytes: Uint8Array) {
  return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("")
}

function normalizeCancelCommand(value: Command): Record<string, string> {
  if (value.tag !== "Cancel") throw new Error("shared fixture did not decode as Command.Cancel")
  return {
    tag: value.tag,
    command_id: value.value.command_id.toString(),
    cancellation_id: value.value.cancellation_id.toString(),
    proposal_id: value.value.proposal_id.toString(),
    scope: value.value.scope.tag,
    cause: value.value.cause.tag,
    requested_at_ms: value.value.requested_at_ms.toString(),
  }
}
